version: '3'
services:
  mail:
    build: .
    volumes:
      - .:/mail
    ports:
      - 3000:3000
    entrypoint: sh /mail/startup.sh
    links:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=mail
