
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mail_development
  host: db
  username: mail
  password: 123456


test:
  <<: *default
  database: mail_test


production:
  <<: *default
  database: mail_production
  username: mail
  password: <%= ENV['MAIL_DATABASE_PASSWORD'] %>
